/*   Script generated by
Lilac Soul's NWN Script Generator, v. 2.3

For download info, please visit:
http://nwvault.ign.com/View.php?view=Other.Detail&id=4683&id=625    */

//Put this on action taken in the conversation editor
void main()
{

object oPC = GetPCSpeaker();


if (GetGold(oPC) >= 80)
    {
        AssignCommand(oPC, TakeGoldFromCreature(80, oPC, TRUE));
    }
    else
     {
         ActionSpeakString("No gold, no food!");
     }

}






